// <auto-generated />
namespace Taskever.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_model_person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_model_person));
        
        string IMigrationMetadata.Id
        {
            get { return "201604210731347_Added_model_person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
