// <auto-generated />
namespace Taskever.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Entity_taskOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entity_taskOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201607090716049_Entity_taskOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
