// <auto-generated />
namespace Taskever.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_seed_orgnization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_seed_orgnization));
        
        string IMigrationMetadata.Id
        {
            get { return "201811300159184_add_seed_orgnization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
