// <auto-generated />
namespace Taskever.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_productModel_to_material : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_productModel_to_material));
        
        string IMigrationMetadata.Id
        {
            get { return "201811300552097_update_productModel_to_material"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
